---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by freeloop.
--- DateTime: 2023/5/20 15:16
---
--- 比较线程标识与锁中的线程标识是否一致
if (redis.call('get', KEYS[1])  == ARGV[1]) then
    --- 一致则释放锁
    return redis.call('del', KEYS[1])
end
--- 不一致 返回0
return 0